# Generated by Django 6.0 on 2026-04-14 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0002_family_description_genus_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='families', to='birds.order'),
        ),
    ]
