# Generated by Django 6.0 on 2026-04-18 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0003_alter_family_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='species',
            old_name='link',
            new_name='cornell_link',
        ),
        migrations.AddField(
            model_name='family',
            name='wikipedia_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='genus',
            name='wikipedia_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='wikipedia_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='wikipedia_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='wikipedia_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
