# Generated by Django 6.0 on 2026-04-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0004_rename_link_species_cornell_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
