# Generated by Django 6.0 on 2026-04-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0005_event_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='species',
            options={'ordering': ['name']},
        ),
        migrations.RemoveIndex(
            model_name='species',
            name='birds_speci_common__1f782b_idx',
        ),
        migrations.RenameField(
            model_name='species',
            old_name='common_name',
            new_name='name',
        ),
        migrations.AddIndex(
            model_name='species',
            index=models.Index(fields=['name'], name='birds_speci_name_eb5cf0_idx'),
        ),
    ]
